@baseUrl = http://localhost:3000/films

###READ ALL FILTERED
GET {{baseUrl}}/?minimum-duration=

###REAL ONE FILM

GET {{baseUrl}}/hbde

###CREATE FILM

POST {{baseUrl}}
Content-Type: application/json

{
    "title":"testcdhs",
    "director":"goerge",
    "duration":134,
    "description":"ubniezub"
}